run: 
	python hello.py $(INPUT)   

clean-pyc:
	find . -name '*.pyc' -exec rm --force {} +
	find . -name '*.pyo' -exec rm --force {} +
	name '*~' -exec rm --force  {} 	

clean-build:
	rm -r build/
	#rm -r *.egg-info